version: "3.8"
services:
  db:
    image: "postgres:17"
    container_name: ${DATABASE_CONTAINER}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db_backups:/var/db_backups
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: naturale-pos
    image: "naturale-pos:latest"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_CONTAINER=${DATABASE_CONTAINER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "80:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:5

  prisma-studio:
    image: oven/bun:1.2-alpine
    working_dir: /usr/src/app
    volumes:
      - ./packages/backend:/usr/src/app
    command: bunx prisma studio --port 5555 --browser none
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    ports:
      - "5555:5555"
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
