import { readdir, readFile, mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { existsSync } from 'fs';

const ROOT_DIR = process.cwd();
const MIGRATIONS_DIR = join(ROOT_DIR, 'prisma', 'migrations');
const OUTPUT_DIR = join(ROOT_DIR, 'src', 'generated');
const OUTPUT_FILE = join(OUTPUT_DIR, 'migrations.ts');

async function generateMigrations() {
  console.log('🔄 Generando módulo embebido de migraciones...');

  if (!existsSync(MIGRATIONS_DIR)) {
    console.warn('⚠️ No se encontró la carpeta prisma/migrations.');
    return;
  }

  const entries = await readdir(MIGRATIONS_DIR, { withFileTypes: true });
  const migrationDirs = entries
    .filter((d) => d.isDirectory())
    .map((d) => d.name)
    .sort(); // Sort chronologically (YYYYMMDDHHMMSS_name)

  const migrations: Array<{ name: string; sql: string }> = [];

  for (const dirName of migrationDirs) {
    const sqlPath = join(MIGRATIONS_DIR, dirName, 'migration.sql');
    if (existsSync(sqlPath)) {
      const sqlContent = await readFile(sqlPath, 'utf-8');
      migrations.push({
        name: dirName,
        sql: sqlContent,
      });
    }
  }

  await mkdir(OUTPUT_DIR, { recursive: true });

  const tsContent = `// Auto-generated by scripts/generate-migrations.ts - DO NOT EDIT MANUALLY
export interface Migration {
  name: string;
  sql: string;
}

export const EMBEDDED_MIGRATIONS: Migration[] = ${JSON.stringify(migrations, null, 2)};
`;

  await writeFile(OUTPUT_FILE, tsContent, 'utf-8');
  console.log(`✅ Migraciones embebidas generadas (${migrations.length} migraciones) en ${OUTPUT_FILE}`);
}

generateMigrations().catch((err) => {
  console.error('❌ Error generando migraciones embebidas:', err);
  process.exit(1);
});
